name: Execute Drawflow

on:
  repository_dispatch:
    types: [run_drawflow]

jobs:
  execute-flow:
    runs-on: ubuntu-latest
    env:
      FLOW_ID: ${{ github.event.client_payload.flowName }}  # ✅ Correctly passing the Flow Name
      SLACK_CHANNEL_ID: ${{ github.event.client_payload.channelId }}  # ✅ Correctly passing the Slack Channel ID
      CALLBACK_URL: ${{ github.event.client_payload.callbackUrl }}
      REQUEST_TYPE: ${{ github.event.client_payload.requestType }}
      EXECUTION_ID: ${{ github.event.client_payload.executionId }}
      PROMPT_TEXT: ${{ github.event.client_payload.promptText }}
      FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios form-data dotenv

      - name: Fetch Drawflow Data & Execute Flow
        env:
          VERCEL_API_URL: "https://j7-magic-tool.vercel.app/api/agentFlowCRUD"
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          echo "📡 Fetching drawflow data for flow ID: $FLOW_ID and sending updates to Slack channel: $SLACK_CHANNEL_ID"
          node chatgptfolder/agentflow/scripts/fetch-drawflow.js
